"""
Extends the sales table forward to today so the dashboard's 30-day
average has data. Daily volumes are derived from each station/fuel
pair's own March 2026 history, with weekday and noise variation.
"""
import re, random, datetime, statistics, pathlib, collections

random.seed(17)

SQL_IN  = pathlib.Path("init-db/init.sql")
SQL_OUT = pathlib.Path("init-db/zz_recent_sales.sql")  # zz_ so MySQL runs it AFTER init.sql

START = datetime.date(2026, 4, 1)
END   = datetime.date.today()

text = SQL_IN.read_text(encoding="utf-8", errors="replace")

# Collect (station, fuel, date, qty) from every sales INSERT
rows = []
for block in re.findall(r"INSERT INTO `sales` VALUES (.*?);\n", text, re.S):
    for m in re.finditer(
        r"\((\d+),(\d+),(\d+),'(\d{4}-\d{2}-\d{2})',([\d.]+)", block
    ):
        _id, st, ft, d, q = m.groups()
        rows.append((int(st), int(ft), d, float(q)))

print(f"parsed {len(rows)} existing sales rows")

# Baseline per (station, fuel) = median daily qty in the last full month
baseline = collections.defaultdict(list)
for st, ft, d, q in rows:
    if d.startswith("2026-03"):
        baseline[(st, ft)].append(q)

pairs = {k: statistics.median(v) for k, v in baseline.items() if v}
print(f"{len(pairs)} station/fuel pairs with a March baseline")

# Highest existing id, so new rows don't collide
max_id = 0
for block in re.findall(r"INSERT INTO `sales` VALUES (.*?);\n", text, re.S):
    for m in re.finditer(r"\((\d+),\d+,\d+,'", block):
        max_id = max(max_id, int(m.group(1)))

WEEKDAY = {0: 1.00, 1: 0.98, 2: 1.02, 3: 1.05, 4: 1.15, 5: 1.10, 6: 0.80}

values, nid = [], max_id + 1
day = START
while day <= END:
    for (st, ft), base in sorted(pairs.items()):
        qty = base * WEEKDAY[day.weekday()] * random.uniform(0.88, 1.12)
        values.append(f"({nid},{st},{ft},'{day}',{qty:.2f},1)")
        nid += 1
    day += datetime.timedelta(days=1)

print(f"generating {len(values)} rows, {START} to {END}")

with SQL_OUT.open("w", encoding="utf-8") as f:
    f.write("-- Generated by scripts/generate-recent-sales.py\n")
    f.write("-- Extends synthetic sales forward so the 30-day dashboard window has data.\n")
    f.write("USE agil_energy;\n\n")
    for i in range(0, len(values), 500):
        chunk = ",".join(values[i:i + 500])
        f.write(
            "INSERT IGNORE INTO `sales` "
            "(id,station_id,fuel_type_id,sale_date,quantity,validated) VALUES "
            + chunk + ";\n"
        )

print(f"wrote {SQL_OUT}")